#
# Copyright The NOMAD Authors.
#
# This file is part of NOMAD. See https://nomad-lab.eu for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Pieces of information relevant for the parsing the ebsd_database use case.

We collected several EBSD datasets from the community. In these studies, names of the
phases used for indexing almost never documented the exact atomic coordinates values
of and all details to the atomic motif and crystal structures explicitly. Instead,
free-text, elements, mineral names, fragments of chemical formulas, names of
mineral groups or rocks are used. The dict maps from these NXphase/name
onto the set of NXem/ENTRY/sampleID[sample]/atom_types.
"""

FREE_TEXT_TO_CONCEPT = {
    "": "n/a",
    "AMS_DATA_Talc_Drits": "Talc",
    "AMS_DATA_Talc_GrunerJW": "Talc",
    "AZ31B": "AZ31B",
    "Acmite": "Aegirine",
    "Actinolite": "Actinolite",
    "Al2 O3": "Al2O3",
    "Albite - mon": "Albite",
    "Albite 1": "Albite",
    "Albite": "Albite",
    "Albite-Sodium Calcium Aluminum Silicate": "Albite",
    "Albite_MS_DATA": "Albite",
    "Almandine": "Almandine",
    "Alumina (alpha)": "Al2O3",
    "Aluminium": "Aluminum",
    "Aluminum": "Aluminum",
    "Amphibole": "Amphibole",
    "Anorthite": "Anorthite",
    "Anorthoclase high": "Anorthoclase",
    "Apatite": "Apatite",
    "Aragonit": "Aragonite",
    "Aragonite": "Aragonite",
    "Arfvedsonite": "Arfvedsonite",
    "Arvfedsonite": "Arfvedsonite",
    "Au hcp": "Au",
    "Augite": "Augite",
    "Austenite": "Fe",
    "Austenite, fcc (New)": "Fe",
    "BYTOWNITE An": "Bytownite",
    "Beta_Ti1023": "Ti",
    "Biotite": "Biotite",
    "Body Centered Cubic": "n/a",
    "Bytownite": "Bytownite",
    "Calcite": "Calcite",
    "Cantor FCC": "CantorAlloy",
    "Chalcopyrite": "Chalopyrite",
    "Chlorapatite": "Chlorapatite",
    "Chlorite Mg12(Si,Al)8": "Chlorite",
    "Chlorite Mg12(Si.Al)8": "Chlorite",
    "Chlorite": "Chlorite",
    "Chloritoid 2M": "Chloritoid",
    "Chromite": "Chromite",
    "Clinochlore 1MIa": "Clinochlore",
    "Clinochlore IIb-2": "Clinochlore",
    "Clinopyroxene": "Clinopyroxene",
    "Clinozoisite": "Clinozoisite",
    "Co FCC": "Co",
    "Co Hexagonal": "Co",
    "Cobalt (alpha)": "Co",
    "Cobalt": "Co",
    "Coesite": "Coesite",
    "Copper": "Cu",
    "Corderite": "Cordierite",
    "Cr": "Cr",
    "Cr2 Al C": "Cr2AlC",
    "Cu Ga Se2": "CuGaSe2",
    "Cu In S2": "CuInS2",
    "Cu In Se2": "CuInSe2",
    "Cu": "Cu",
    "Diopside   CaMgSi2O6": "Diopside",
    "Diopside": "Diopside",
    "Dolomite": "Dolomite",
    "Enstatite  Opx AV77": "Enstatite",
    "Enstatite": "Enstatite",
    "Epidote": "Epidote",
    "Epidote, ferrian": "Epidote",
    "Epsilon_Martensite": "Fe",
    "Eudialyte": "Eudialyte",
    "Face Centered Cubic": "n/a",
    "Fe": "Fe",
    "Fe-BCC": "Fe",
    "Fe-FCC": "Fe",
    "Fe3C": "Fe3C",
    "Feldspar": "Feldspar",
    "Ferrite": "Fe",
    "Ferrite, bcc (New)": "Fe",
    "Ferrite, bcc 110 (old)": "Fe",
    "Ferrite, bcc": "Fe",
    "Ferrosilite, magnesian": "Ferrosilite",
    "Fluorapatite": "Fluorapatite",
    "Fluorite": "Fluorite",
    "Forsterite , 90%Mg": "Forsterite",
    "Forsterite": "Forsterite",
    "Ga N": "GaN",
    "Gallium nitride": "GaN",
    "Garnet - (Mg,Ni)3Al2(": "Garnet",
    "Garnet": "Garnet",
    "Glaucophane": "Glaucophane",
    "Gold": "Au",
    "Graphite": "Graphite",
    "Grossular": "Grossular",
    "Halite": "Halite",
    "Hematite": "Hematite",
    "Hornblende  C2/m": "Hornblende",
    "Hornblende": "Hornblende",
    "Hortonolite": "Hortonolite",
    "Hydroxylapatite": "Hydroxylapatite",
    "ICSD 105250-TiNb": "TiNb",
    "Ice 1h": "H2O",
    "Ice Ih": "H2O",
    "Ice1h": "H2O",
    "Ilmenite - MgSiO3": "Ilmenite",
    "Ilmenite FeTiO3 trig": "Ilmenite",
    "Ilmenite": "Ilmenite",
    "Iron (Alpha)": "Fe",
    "Iron (Gamma)": "Fe",
    "Iron - Alpha": "Fe",
    "Iron Oxide (C)": "Iron oxide",
    "Iron bcc (old)": "Fe",
    "Iron carbide": "Iron carbide",
    "Iron fcc": "Fe",
    "Iron": "Fe",
    "Jadeite": "Jadeite",
    "K Fsp": "Orthoclase",
    "Kyanite": "Kyanite",
    "Labradorite": "Labradorite",
    "Lawsonite": "Lawsonite",
    "Low albite": "Albite",
    "Magnesite": "Magnesite",
    "Magnesium": "Mg",
    "Magnetite low": "Magnetite",
    "Magnetite": "Magnetite",
    "MagnetiteFe3O4 Fd3m": "Magnetite",
    "Merrillite": "Merrillite",
    "Mg Zn2": "MgZn2",
    "Mg": "Mg",
    "Mg2 Zn11": "Mg2Zn11",
    "MgSiO3 pv (DY)": "Enstatite",
    "Microcline": "Microcline",
    "Mullite": "Mullite",
    "Muscovite - 2M1": "Muscovite",
    "Muscovite 2M1": "Muscovite",
    "Muscovite": "Muscovite",
    "N Ti": "TiN",
    "N Zr": "ZrN",
    "Nb": "Nb",
    "Nepheline": "Nepheline",
    "Ni Ti": "NiTi",
    "Ni": "Ni",
    "Ni-Alloy": "Ni-Alloy",
    "Ni-superalloy": "Ni",
    "Ni3Al": "Ni3Al",
    "NiTi austenite": "NiTi",
    "NiTi martensite": "NiTi",
    "NiTi martensite2": "NiTi",
    "Nickel": "Ni",
    "OR X": "n/a",
    "Oligoclase": "Oligoclase",
    "Olivine": "Olivine",
    "Omphacite": "Omphacite",
    "Orthoclase inverted": "Orthoclase",
    "Orthoclase": "Orthoclase",
    "Orthopyroxene": "Orthopyroxene",
    "Pargasite C2/m": "Pargasite",
    "Pargasite": "Pargasite",
    "Pentlandite": "Pentlandite",
    "Periclase": "Periclase",
    "Phase 22474944": "n/a",
    "Phase D": "n/a",
    "Phase_1": "n/a",
    "Pigeonite": "Pigeonite",
    "Plagioclase": "Plagioclase",
    "Prehnite": "Prehnite",
    "Pumpellyite": "Pumpellyite",
    "Pyrite": "Pyrite",
    "Pyrope": "Pyrope",
    "Pyroxene": "Augite",
    "Quartz low": "Quartz",
    "Quartz": "Quartz",
    "Quartz-new": "Quartz",
    "Quartz_hex": "Quartz",
    "Quartz_mod": "Quartz",
    "Ringwoodite": "Ringwoodite",
    "Rutile": "Rutile",
    "Sanidine": "Sanidine",
    "Siderite": "Siderite",
    "Sigma Fe Cr Mo": "SigmaFeCrMo",
    "Sigma phase _CrFe": "FeCr",
    "Silicon": "Si",
    "Silver": "Ag",
    "Sodalite": "Sodalite",
    "Spessartine, ferroan": "Spessartine",
    "Spinel - (Mg,Fe)2SiO4": "Spinel",
    "Spinel": "Spinel",
    "Stishovite": "Stishovite",
    "Sulfoapatite": "Sulfoapatite",
    "Superalloy-MC": "n/a",
    "Ta": "Ta",
    "Tantalum": "Ta",
    "Ti (BETA)": "Ti",
    "Ti (alpha)": "Ti",
    "Ti O": "TiO",
    "Ti O2 (anatase)": "TiO2",
    "Ti O2": "TiO2",
    "Ti-Hex": "Ti",
    "Ti-adp": "Ti",
    "Ti2448-adp": "Ti",
    "Ti2448-beta": "Ti",
    "TiC": "TiC",
    "TiMo CMCM Fan": "TiMo",
    "Ti_JOMTAA_corrected": "Ti",
    "Tin": "Sn",
    "Titanite": "Titanite",
    "Titanium Beta": "Ti",
    "Titanium cubic": "Ti",
    "Titanium": "Ti",
    "Titanium-beta": "Ti",
    "Tremolite": "Tremolite",
    "Troilite": "Troilite",
    "W": "W",
    "Wadsleyite": "Wadsleyite",
    "Whitlockite": "Whitlockite",
    "YBCO 211": "YBCO",
    "Zeolite": "Zeolite",
    "Zinc": "Zn",
    "Zirc-alloy4": "Zirc-alloy4",
    "Zircon": "Zr",
    "Zirconia tetragonal": "Zirconia",
    "Zirconium - alpha": "Zr",
    "Zirconium": "Zr",
    "Zoisite": "Zoisite",
    "Zr": "Zr",
    "Zr02 monoclinic": "ZrO",
    "ZrFeCr2_hex": "ZrFeCr2",
    "ZrH": "ZrH",
    "ZrH-_fcc": "ZrH",
    "Zr_hex": "Zr",
    "al": "Al",
    "calcite": "Calcite",
    "deltaAlOOH_amcsd00084": "AlOOH",
    "deltaAlOOH_amcsd0008490": "AlOOH",
    "delta_AlOOH_amcsd 000": "AlOOH",
    "gamma": "n/a",
    "kamacite": "Kamacite",
    "lo-albite": "Albite",
    "martensite_Ti1023": "Ti",
    "notIndexed": "notIndexed",
    "olivine": "Olivine",
    "ompaciteP2n": "Omphacite",
    "omphacite": "Omphacite",
    "taenite": "Taenite",
    "troilite": "Troilite",
}


CONCEPT_TO_ATOM_TYPES = {
    "AZ31B": "Mg;Al;Zn",
    "Actinolite": "Ca;Mg;Fe;Si;O;H",
    "Aegirine": "Na;Fe;Si;O",
    "Al": "Al",
    "Al2O3": "Al;O",
    "AlOOH": "Al;O;H",
    "Albite": "Na;Al;Si;O",
    "Almandine": "Fe;Si;Al;O",
    "Aluminum": "Al",
    "Amphibole": "Si;O;H",
    "Anorthite": "Ca;Al;Si;O",
    "Anorthoclase": "Na;K;Al;Si;O",
    "Apatite": "P;O",
    "Aragonite": "Ca;C;O",
    "Arfvedsonite": "Na;Fe;Si;O;H",
    "Au": "Au",
    "Augite": "Ca;Mg;Fe;Si;O",
    "Biotite": "K;Si;O",
    "Bytownite": "Ca;Na;Si;Al;O",
    "Calcite": "Ca;C;O",
    "CantorAlloy": "Cr;Mn;Fe;Co;Ni",
    "Chalopyrite": "Cu;Fe;S",
    "Chlorapatite": "Ca;P;O;Cl",
    "Chlorite": "Fe;Mg;Al;Si;Al;O;H",
    "Chloritoid": "Fe;Al;O;Si;H",
    "Chromite": "Fe;Cr;O",
    "Clinochlore": "Mg;Al;Si;O;H",
    "Clinopyroxene": "Si;O",
    "Clinozoisite": "Ca;Al;Si;O;H",
    "Co": "Co",
    "Coesite": "Si;O",
    "Cordierite": "Mg;Al;Si;O",
    "Cr": "Cr",
    "Cr2AlC": "Cr;Al;C",
    "Cu": "Cu",
    "CuGaSe2": "Cu;Ga;Se",
    "CuInS2": "Cu;In;S",
    "CuInSe2": "Cu;In;Se",
    "Diopside": "Ca;Mg;Si;O",
    "Dolomite": "Ca;Mg;C;O",
    "Enstatite": "Mg;Si;O",
    "Epidote": "Ca;Al;Fe;Si;O;H",
    "Eudialyte": "Na;Ca;Fe;Zr;Si;O;H;Cl",
    "Fe": "Fe",
    "Fe3C": "Fe;C",
    "FeCr": "Fe;Cr",
    "Feldspar": "Si;O",
    "Ferrosilite": "Fe;Si;O",
    "Fluorapatite": "Ca;P;O;F",
    "Fluorite": "Ca;F",
    "Forsterite": "Mg;Si;O",
    "GaN": "Ga;N",
    "Garnet": "Si;O",
    "Glaucophane": "Na;Mg;Al;Si;O;H",
    "Graphite": "C",
    "Grossular": "Ca;Al;Si;O",
    "H2O": "H;O",
    "Halite": "Na;Cl",
    "Hematite": "Fe;O",
    "Hornblende": "Al;Si;O",
    "Hortonolite": "Fe;Si;O",
    "Hydroxylapatite": "Ca;P;O;H",
    "Ilmenite": "Fe;Ti;O",
    "Iron carbide": "Fe;C",
    "Iron oxide": "Fe;O",
    "Jadeite": "Na;Al;Si;O",
    "Kamacite": "Fe;Ni",
    "Kyanite": "Al;O;Si",
    "Labradorite": "Ca;Na;Si;Al;O",
    "Lawsonite": "Ca;Al;Si;O;H",
    "Magnesite": "Mg;C;O",
    "Magnetite": "Fe;O",
    "Merrillite": "Ca;Na;Mg;P;O",
    "Mg": "Mg",
    "Mg2Zn11": "Mg;Zn",
    "MgZn2": "Mg;Zn",
    "Microcline": "K;Al;Si;O",
    "Mullite": "Al;Si;O",
    "Muscovite": "K;Al;Si;O;H",
    "Nb": "Nb",
    "Nepheline": "Na;K;Al;Si;O",
    "Ni": "Ni",
    "Ni-Alloy": "Ni",
    "Ni3Al": "Ni;Al",
    "NiTi": "Ni;Ti",
    "Oligoclase": "Na;Ca;Si;Al;O",
    "Olivine": "Mg;Fe;Si;O",
    "Omphacite": "Ca;Na;Mg;Fe;Al;Si;O",
    "Orthoclase": "K;Al;Si;O",
    "Orthopyroxene": "Mg;Si;O",
    "Pargasite": "Na;Ca;Mg;Al;Si;O;H",
    "Pentlandite": "Ni;Fe;S",
    "Periclase": "Mg;O",
    "Pigeonite": "Mg;Fe;Ca;Si;O",
    "Plagioclase": "Al;Si;O",
    "Prehnite": "Ca;Al;Si;O;H",
    "Pumpellyite": "Ca;Si;O;H",
    "Pyrite": "Fe;S",
    "Pyrope": "Mg;Al;Si;O",
    "Quartz": "Si;O",
    "Ringwoodite": "Si;Mg;O",
    "Rutile": "Ti;O",
    "Sanidine": "K;Al;Si;O",
    "Si": "Si",
    "Siderite": "Fe;C;O",
    "SigmaFeCrMo": "Fe;Cr;Mo",
    "Sn": "Sn",
    "Sodalite": "Na;Is;Al;O;Cl",
    "Spessartine": "Mn;Al;Si;O",
    "Spinel": "Mg;Al;O",
    "Stishovite": "Si;O",
    "Sulfoapatite": "S;P;O",
    "Ta": "Ta",
    "Taenite": "Ni;Fe",
    "Talc": "Mg;Al;O;H;C",
    "Ti": "Ti",
    "TiC": "Ti;C",
    "TiMo": "Ti;Mo",
    "TiN": "Ti;N",
    "TiNb": "Ti;Nb",
    "TiO": "Ti;O",
    "TiO2": "Ti;O",
    "Titanite": "Ca;Ti;Si;O",
    "Tremolite": "Ca;Mg;Fe;Si;O;H",
    "Troilite": "Fe;S",
    "W": "W",
    "Wadsleyite": "Mg;Si;O",
    "Whitlockite": "Ca;Mg;P;O;H",
    "YBCO": "Y;Ba;Cu;O",
    "Zeolite": "",
    "Zirc-alloy4": "Zr;Sn;Fe;Cr",
    "Zircon": "Zr;Si;O",
    "Zirconia": "Zr;O",
    "Zn": "Zn",
    "Zoisite": "Ca;Al;Si;O;H",
    "Zr": "Zr",
    "ZrFeCr2": "Zr;Fe;Cr",
    "ZrH": "Zr;H",
    "ZrN": "Zr;N",
    "ZrO": "Zr;O",
    "n/a": "",
    "notIndexed": "",
}


ASSUME_PHASE_NAME_TO_SPACE_GROUP = {
    "Silver": 225,
    "Copper": 225,
    "Ni (Nickel)": 225,
    "Face Centered Cubic": 225,
    "Ge (Germanium)": 225,
}  # Ge (Germanium), really?
