name: linting

on: [push]

env:
  UV_SYSTEM_PYTHON: true
jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install ".[dev,docs]"
      - name: ruff check
        run: |
          ruff check src/pynxtools_em tests
      - name: ruff formatting
        run: |
          ruff format --check src/pynxtools_em tests
      - name: mypy
        run: |
          mypy src/pynxtools_em tests
