name: pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install uv and set the python version to ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install nomad
        if: "${{ matrix.python_version != '3.13' }}"
        run: |
          uv pip install nomad-lab[infrastructure]@git+https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR.git
      - name: Install package
        run: |
          uv pip install ".[dev]"
      - name: Install pynxtools master branch
        run: |
          uv pip install pynxtools@git+https://github.com/FAIRmat-NFDI/pynxtools
      - name: Test with pytest
        run: |
          pytest -sv --show-capture=no tests
        #  coverage run -m pytest -sv --show-capture=no tests
      # - name: Submit to coveralls
      #   continue-on-error: true
      #   env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #       coveralls --service=github
